# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'operation_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_login(object):
    def setupUi(self, Form_login):
        Form_login.setObjectName("Form_login")
        Form_login.resize(400, 200)
        Form_login.setFixedSize(400, 200)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form_login)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_login_title = QtWidgets.QLabel(Form_login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_login_title.sizePolicy().hasHeightForWidth())
        self.label_login_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_login_title.setFont(font)
        self.label_login_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_login_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login_title.setObjectName("label_login_title")
        self.verticalLayout_3.addWidget(self.label_login_title)
        spacerItem = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(Form_login)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_login_user = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_login_user.setFont(font)
        self.label_login_user.setObjectName("label_login_user")
        self.verticalLayout.addWidget(self.label_login_user)
        self.label_login_password = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_login_password.setFont(font)
        self.label_login_password.setObjectName("label_login_password")
        self.verticalLayout.addWidget(self.label_login_password)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_login_user = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)

        self.user_reg = QtCore.QRegExp('[0-9]+$')
        self.user_validator = QtGui.QRegExpValidator(self.user_reg)

        self.pwd_reg = QtCore.QRegExp('[a-zA-z0-9]+$')
        self.pwd_validator = QtGui.QRegExpValidator(self.pwd_reg)

        self.lineEdit_login_user.setFont(font)
        self.lineEdit_login_user.setStyleSheet("border: 1px solid gray;   /* 边框 */\n"
                                               "border-radius: 3px;   /* 圆角 */\n"
                                               "padding: 1px 18px 1px 3px;\n"
                                               "")
        self.lineEdit_login_user.setText("")
        self.lineEdit_login_user.setObjectName("lineEdit_login_user")
        self.lineEdit_login_user.setValidator(self.user_validator)
        self.verticalLayout_2.addWidget(self.lineEdit_login_user)
        self.lineEdit_login_password = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_login_password.setFont(font)
        self.lineEdit_login_password.setStyleSheet("border: 1px solid gray;   /* 边框 */\n"
                                                   "border-radius: 3px;   /* 圆角 */\n"
                                                   "padding: 1px 18px 1px 3px;\n"
                                                   "")
        self.lineEdit_login_password.setText("")
        self.lineEdit_login_password.setObjectName("lineEdit_login_password")
        self.lineEdit_login_password.setValidator(self.pwd_validator)
        self.verticalLayout_2.addWidget(self.lineEdit_login_password)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(69, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.widget)
        spacerItem3 = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pushButton_login = QtWidgets.QPushButton(Form_login)
        self.pushButton_login.setStyleSheet("QPushButton{\n"
                                            "border: 1px solid gray;   /* 边框 */\n"
                                            "border-radius: 3px;   /* 圆角 */\n"
                                            "}\n"
                                            "QPushButton:hover{background-color:pink;}\n"
                                            "QPushButton:pressed{background-color:#F0F0F0;}")
        self.pushButton_login.setObjectName("pushButton_login")
        # self.pushButton_login.clicked.connect(self.login_submit)
        self.horizontalLayout_3.addWidget(self.pushButton_login)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.pushButton_exit = QtWidgets.QPushButton(Form_login)
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
                                           "border: 1px solid gray;   /* 边框 */\n"
                                           "border-radius: 3px;   /* 圆角 */\n"
                                           "}\n"
                                           "QPushButton:hover{background-color:pink;}\n"
                                           "QPushButton:pressed{background-color:#F0F0F0;}")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.horizontalLayout_3.addWidget(self.pushButton_exit)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 2)
        self.horizontalLayout_3.setStretch(4, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)

        self.retranslateUi(Form_login)
        self.pushButton_exit.clicked.connect(Form_login.close)
        QtCore.QMetaObject.connectSlotsByName(Form_login)

    def retranslateUi(self, Form_login):
        _translate = QtCore.QCoreApplication.translate
        Form_login.setWindowTitle(_translate("Form_login", "Login"))
        self.label_login_title.setText(_translate("Form_login", "职 位 匹 配 器"))
        self.label_login_user.setText(_translate("Form_login", "用户名："))
        self.label_login_password.setText(_translate("Form_login", "密  码："))
        self.pushButton_login.setText(_translate("Form_login", "登录"))
        self.pushButton_exit.setText(_translate("Form_login", "退出"))

    # 返回输入账户/密码
    def login_submit(self):
        # print(self.lineEdit_login_user.text(), self.lineEdit_login_password.text())
        return self.lineEdit_login_user.text(), self.lineEdit_login_password.text()
        # un, pwd = self.lineEdit_login_user.text(), self.lineEdit_login_password.text()
        # a(True)

    def logging_in(self):
        QtWidgets.QMessageBox.information(self.widget, 'Loading', '请稍等，登陆中...')

    # 登陆失败弹出提示框
    def login_determine(self):
        QtWidgets.QMessageBox.information(self.widget, 'Tip', '请重新输入用户名/密码')


class Ui_widget_main_window(object):
    search_terms_dict = {
        'search_terms': 'None',
        'famous_enterprise': '',
        'target_city_section': ['', ''],
        'expected_salary': ['', '', ''],
        'release_time': '',
        'work_experience': '',
        'education': '',
        'expected_industry': ['', ''],
        'expected_position': '',
        'enterprise_scale': '',
        'financing_stage': '',
        'enterprise_nature': ''
    }

    def setupUi(self, widget_main_window):
        widget_main_window.setObjectName("widget_main_window")
        widget_main_window.resize(1112, 625)
        widget_main_window.setFixedSize(1112, 625)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(widget_main_window.sizePolicy().hasHeightForWidth())
        widget_main_window.setSizePolicy(sizePolicy)
        widget_main_window.setToolTip("")
        widget_main_window.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(widget_main_window)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(widget_main_window)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.lineEdit_search_keys = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_search_keys.sizePolicy().hasHeightForWidth())
        self.lineEdit_search_keys.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_search_keys.setFont(font)
        self.lineEdit_search_keys.setStyleSheet("border-radius: 10px;\n"
                                                "border: 2px groove gray;")
        self.lineEdit_search_keys.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_search_keys.setObjectName("lineEdit_search_keys")
        self.lineEdit_search_keys.editingFinished.connect(self.search_keys)
        self.horizontalLayout_4.addWidget(self.lineEdit_search_keys)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.widget_famous_enterprise = QtWidgets.QWidget(self.groupBox)
        self.widget_famous_enterprise.setObjectName("widget_famous_enterprise")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_famous_enterprise)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_famous_enterprise = QtWidgets.QLabel(self.widget_famous_enterprise)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_famous_enterprise.setFont(font)
        self.label_famous_enterprise.setAlignment(QtCore.Qt.AlignCenter)
        self.label_famous_enterprise.setObjectName("label_famous_enterprise")
        self.horizontalLayout_16.addWidget(self.label_famous_enterprise)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_famous_enterprise_1 = My_QRadioButton(self.widget_famous_enterprise)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_famous_enterprise_1.setFont(font)
        self.radioButton_famous_enterprise_1.setCheckable(True)
        self.radioButton_famous_enterprise_1.setObjectName("radioButton_famous_enterprise_1")
        self.radioButton_famous_enterprise_1.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                           "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.radioButton_famous_enterprise_1.clicked.connect(self.famous_enterprise)
        self.horizontalLayout.addWidget(self.radioButton_famous_enterprise_1)
        self.radioButton_famous_enterprise_2 = My_QRadioButton(self.widget_famous_enterprise)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_famous_enterprise_2.setFont(font)
        self.radioButton_famous_enterprise_2.setObjectName("radioButton_famous_enterprise_2")
        self.radioButton_famous_enterprise_2.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                           "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.radioButton_famous_enterprise_2.clicked.connect(self.famous_enterprise)
        self.horizontalLayout.addWidget(self.radioButton_famous_enterprise_2)
        self.radioButton_famous_enterprise_3 = My_QRadioButton(self.widget_famous_enterprise)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_famous_enterprise_3.setFont(font)
        self.radioButton_famous_enterprise_3.setObjectName("radioButton_famous_enterprise_3")
        self.radioButton_famous_enterprise_3.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                           "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.radioButton_famous_enterprise_3.clicked.connect(self.famous_enterprise)
        self.horizontalLayout.addWidget(self.radioButton_famous_enterprise_3)
        self.radioButton_famous_enterprise_4 = My_QRadioButton(self.widget_famous_enterprise)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_famous_enterprise_4.setFont(font)
        self.radioButton_famous_enterprise_4.setObjectName("radioButton_famous_enterprise_4")
        self.radioButton_famous_enterprise_4.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                           "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.radioButton_famous_enterprise_4.clicked.connect(self.famous_enterprise)
        self.horizontalLayout.addWidget(self.radioButton_famous_enterprise_4)
        self.radioButton_famous_enterprise_5 = My_QRadioButton(self.widget_famous_enterprise)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_famous_enterprise_5.setFont(font)
        self.radioButton_famous_enterprise_5.setObjectName("radioButton_famous_enterprise_5")
        self.radioButton_famous_enterprise_5.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                           "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.radioButton_famous_enterprise_5.clicked.connect(self.famous_enterprise)
        self.horizontalLayout.addWidget(self.radioButton_famous_enterprise_5)
        self.radioButton_famous_enterprise_6 = My_QRadioButton(self.widget_famous_enterprise)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_famous_enterprise_6.setFont(font)
        self.radioButton_famous_enterprise_6.setObjectName("radioButton_famous_enterprise_6")
        self.radioButton_famous_enterprise_6.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                           "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.radioButton_famous_enterprise_6.clicked.connect(self.famous_enterprise)
        self.horizontalLayout.addWidget(self.radioButton_famous_enterprise_6)
        self.horizontalLayout_16.addLayout(self.horizontalLayout)
        self.horizontalLayout_16.setStretch(0, 1)
        self.horizontalLayout_16.setStretch(1, 9)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_16)
        self.verticalLayout.addWidget(self.widget_famous_enterprise)
        self.line_row_1 = QtWidgets.QFrame(self.groupBox)
        self.line_row_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_row_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_row_1.setObjectName("line_row_1")
        self.verticalLayout.addWidget(self.line_row_1)
        self.widget_target_city = QtWidgets.QWidget(self.groupBox)
        self.widget_target_city.setObjectName("widget_target_city")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_target_city)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_target_city = QtWidgets.QLabel(self.widget_target_city)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_target_city.setFont(font)
        self.label_target_city.setAlignment(QtCore.Qt.AlignCenter)
        self.label_target_city.setObjectName("label_target_city")
        self.horizontalLayout_15.addWidget(self.label_target_city)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_target_city_default = QtWidgets.QLabel(self.widget_target_city)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_target_city_default.sizePolicy().hasHeightForWidth())
        self.label_target_city_default.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_target_city_default.setFont(font)
        self.label_target_city_default.setAlignment(QtCore.Qt.AlignCenter)
        self.label_target_city_default.setObjectName("label_target_city_default")
        self.horizontalLayout_9.addWidget(self.label_target_city_default)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_15.setStretch(0, 1)
        self.horizontalLayout_15.setStretch(1, 9)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_15)
        self.verticalLayout.addWidget(self.widget_target_city)
        self.line_row_2 = QtWidgets.QFrame(self.groupBox)
        self.line_row_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_row_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_row_2.setObjectName("line_row_2")
        self.verticalLayout.addWidget(self.line_row_2)
        self.widget_expected_salary = QtWidgets.QWidget(self.groupBox)
        self.widget_expected_salary.setObjectName("widget_expected_salary")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_expected_salary)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_expected_salary = QtWidgets.QLabel(self.widget_expected_salary)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_expected_salary.setFont(font)
        self.label_expected_salary.setAlignment(QtCore.Qt.AlignCenter)
        self.label_expected_salary.setObjectName("label_expected_salary")
        self.horizontalLayout_14.addWidget(self.label_expected_salary)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_expected_salary_1 = My_QRadioButton(self.widget_expected_salary)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_expected_salary_1.setFont(font)
        self.radioButton_expected_salary_1.setObjectName("radioButton_expected_salary_1")
        self.radioButton_expected_salary_1.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                           "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.radioButton_expected_salary_1.clicked.connect(self.expected_salary_defined)
        # self.radioButton_expected_salary_1.double_connect_customized_slot(self.expected_salary_defined)
        # self.radioButton_expected_salary_1.toggled.connect(self.expected_salary_defined)
        self.horizontalLayout_5.addWidget(self.radioButton_expected_salary_1)
        self.radioButton_expected_salary_2 = My_QRadioButton(self.widget_expected_salary)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_expected_salary_2.setFont(font)
        self.radioButton_expected_salary_2.setObjectName("radioButton_expected_salary_2")
        self.radioButton_expected_salary_2.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                         "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.radioButton_expected_salary_2.clicked.connect(self.expected_salary_defined)
        # self.radioButton_expected_salary_2.double_connect_customized_slot(self.expected_salary_defined)
        # self.radioButton_expected_salary_2.toggled.connect(self.expected_salary_defined)
        self.horizontalLayout_5.addWidget(self.radioButton_expected_salary_2)
        self.radioButton_expected_salary_3 = My_QRadioButton(self.widget_expected_salary)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_expected_salary_3.setFont(font)
        self.radioButton_expected_salary_3.setObjectName("radioButton_expected_salary_3")
        self.radioButton_expected_salary_3.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                         "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.radioButton_expected_salary_3.clicked.connect(self.expected_salary_defined)
        # self.radioButton_expected_salary_3.double_connect_customized_slot(self.expected_salary_defined)
        self.horizontalLayout_5.addWidget(self.radioButton_expected_salary_3)
        self.radioButton_expected_salary_4 = My_QRadioButton(self.widget_expected_salary)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_expected_salary_4.setFont(font)
        self.radioButton_expected_salary_4.setObjectName("radioButton_expected_salary_4")
        self.radioButton_expected_salary_4.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                         "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.radioButton_expected_salary_4.clicked.connect(self.expected_salary_defined)
        # self.radioButton_expected_salary_4.double_connect_customized_slot(self.expected_salary_defined)
        self.horizontalLayout_5.addWidget(self.radioButton_expected_salary_4)
        self.radioButton_expected_salary_5 = My_QRadioButton(self.widget_expected_salary)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_expected_salary_5.setFont(font)
        self.radioButton_expected_salary_5.setObjectName("radioButton_expected_salary_5")
        self.radioButton_expected_salary_5.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                         "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.radioButton_expected_salary_5.clicked.connect(self.expected_salary_defined)
        # self.radioButton_expected_salary_5.double_connect_customized_slot(self.expected_salary_defined)
        self.horizontalLayout_5.addWidget(self.radioButton_expected_salary_5)
        self.radioButton_expected_salary_6 = My_QRadioButton(self.widget_expected_salary)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_expected_salary_6.setFont(font)
        self.radioButton_expected_salary_6.setObjectName("radioButton_expected_salary_6")
        self.radioButton_expected_salary_6.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                         "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.radioButton_expected_salary_6.clicked.connect(self.expected_salary_defined)
        # self.radioButton_expected_salary_6.double_connect_customized_slot(self.expected_salary_defined)
        self.horizontalLayout_5.addWidget(self.radioButton_expected_salary_6)
        self.radioButton_expected_salary_7 = My_QRadioButton(self.widget_expected_salary)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_expected_salary_7.setFont(font)
        self.radioButton_expected_salary_7.setObjectName("radioButton_expected_salary_7")
        self.radioButton_expected_salary_7.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                         "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.radioButton_expected_salary_7.clicked.connect(self.expected_salary_defined)
        # self.radioButton_expected_salary_7.double_connect_customized_slot(self.expected_salary_defined)
        self.horizontalLayout_5.addWidget(self.radioButton_expected_salary_7)
        self.groupBox_expected_salary_defined = QtWidgets.QGroupBox(self.widget_expected_salary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_expected_salary_defined.sizePolicy().hasHeightForWidth())
        self.groupBox_expected_salary_defined.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_expected_salary_defined.setFont(font)
        self.groupBox_expected_salary_defined.setStyleSheet("")
        self.groupBox_expected_salary_defined.setObjectName("groupBox_expected_salary_defined")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_expected_salary_defined)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.intValidator = QtGui.QIntValidator()
        self.intValidator.setRange(1, 99)

        self.lineEdit_expected_salary_defined_first = QtWidgets.QLineEdit(self.groupBox_expected_salary_defined)
        self.lineEdit_expected_salary_defined_first.setStyleSheet("border-radius: 10px;  border: 2px groove gray;")
        self.lineEdit_expected_salary_defined_first.setObjectName("lineEdit_expected_salary_defined_first")
        self.lineEdit_expected_salary_defined_first.setValidator(self.intValidator)
        self.horizontalLayout_2.addWidget(self.lineEdit_expected_salary_defined_first)
        self.label_expected_salary_k1 = QtWidgets.QLabel(self.groupBox_expected_salary_defined)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_expected_salary_k1.setFont(font)
        self.label_expected_salary_k1.setStyleSheet("")
        self.label_expected_salary_k1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_expected_salary_k1.setObjectName("label_expected_salary_k1")
        self.horizontalLayout_2.addWidget(self.label_expected_salary_k1)
        self.line_expected_salary_solid = QtWidgets.QFrame(self.groupBox_expected_salary_defined)
        self.line_expected_salary_solid.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_expected_salary_solid.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_expected_salary_solid.setObjectName("line_expected_salary_solid")
        self.horizontalLayout_2.addWidget(self.line_expected_salary_solid)
        self.lineEdit_expected_salary_defined_second = QtWidgets.QLineEdit(self.groupBox_expected_salary_defined)
        self.lineEdit_expected_salary_defined_second.setStyleSheet("border-radius: 10px;  border: 2px groove gray;")
        self.lineEdit_expected_salary_defined_second.setObjectName("lineEdit_expected_salary_defined_second")
        self.lineEdit_expected_salary_defined_second.setValidator(self.intValidator)
        self.horizontalLayout_2.addWidget(self.lineEdit_expected_salary_defined_second)
        self.label_expected_salary_k2 = QtWidgets.QLabel(self.groupBox_expected_salary_defined)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_expected_salary_k2.setFont(font)
        self.label_expected_salary_k2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_expected_salary_k2.setObjectName("label_expected_salary_k2")
        self.horizontalLayout_2.addWidget(self.label_expected_salary_k2)
        self.pushButton_expected_salary_defined = QtWidgets.QPushButton(self.groupBox_expected_salary_defined)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_expected_salary_defined.setFont(font)
        self.pushButton_expected_salary_defined.setStyleSheet("QPushButton{border-radius: 3px; \n"
                                                              "border: 1px solid gray;}"
                                                              "QPushButton:hover{background-color:pink;}"
                                                              "QPushButton:pressed{background-color:#F0F0F0;}")
        self.pushButton_expected_salary_defined.setObjectName("pushButton_expected_salary_defined")
        self.pushButton_expected_salary_defined.clicked.connect(self.expected_salary_defined)
        self.horizontalLayout_2.addWidget(self.pushButton_expected_salary_defined)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 3)
        self.horizontalLayout_2.setStretch(4, 1)
        self.horizontalLayout_2.setStretch(5, 3)
        self.horizontalLayout_5.addWidget(self.groupBox_expected_salary_defined)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.horizontalLayout_5.setStretch(3, 1)
        self.horizontalLayout_5.setStretch(4, 1)
        self.horizontalLayout_5.setStretch(5, 1)
        self.horizontalLayout_5.setStretch(6, 1)
        self.horizontalLayout_5.setStretch(7, 3)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 9)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_14)
        self.verticalLayout.addWidget(self.widget_expected_salary)
        self.line_row_3 = QtWidgets.QFrame(self.groupBox)
        self.line_row_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_row_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_row_3.setObjectName("line_row_3")
        self.verticalLayout.addWidget(self.line_row_3)
        self.widget_release_time = QtWidgets.QWidget(self.groupBox)
        self.widget_release_time.setObjectName("widget_release_time")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_release_time)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_release_time = QtWidgets.QLabel(self.widget_release_time)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_release_time.setFont(font)
        self.label_release_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_release_time.setObjectName("label_release_time")
        self.horizontalLayout_13.addWidget(self.label_release_time)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButton_release_time_1 = My_QRadioButton(self.widget_release_time)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_release_time_1.setFont(font)
        self.radioButton_release_time_1.setObjectName("radioButton_release_time_1")
        self.radioButton_release_time_1.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                      "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.radioButton_release_time_1.clicked.connect(self.release_time)
        self.horizontalLayout_8.addWidget(self.radioButton_release_time_1)
        self.radioButton_release_time_2 = My_QRadioButton(self.widget_release_time)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_release_time_2.setFont(font)
        self.radioButton_release_time_2.setObjectName("radioButton_release_time_2")
        self.radioButton_release_time_2.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                      "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.radioButton_release_time_2.clicked.connect(self.release_time)
        self.horizontalLayout_8.addWidget(self.radioButton_release_time_2)
        self.radioButton_release_time_3 = My_QRadioButton(self.widget_release_time)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_release_time_3.setFont(font)
        self.radioButton_release_time_3.setObjectName("radioButton_release_time_3")
        self.radioButton_release_time_3.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                      "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.radioButton_release_time_3.clicked.connect(self.release_time)
        self.horizontalLayout_8.addWidget(self.radioButton_release_time_3)
        self.radioButton_release_time_4 = My_QRadioButton(self.widget_release_time)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_release_time_4.setFont(font)
        self.radioButton_release_time_4.setObjectName("radioButton_release_time_4")
        self.radioButton_release_time_4.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                      "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.radioButton_release_time_4.clicked.connect(self.release_time)
        self.horizontalLayout_8.addWidget(self.radioButton_release_time_4)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 9)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addWidget(self.widget_release_time)
        self.line_row_4 = QtWidgets.QFrame(self.groupBox)
        self.line_row_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_row_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_row_4.setObjectName("line_row_4")
        self.verticalLayout.addWidget(self.line_row_4)
        self.widget_work_experience = QtWidgets.QWidget(self.groupBox)
        self.widget_work_experience.setObjectName("widget_work_experience")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.widget_work_experience)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_work_experience = QtWidgets.QLabel(self.widget_work_experience)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_work_experience.setFont(font)
        self.label_work_experience.setAlignment(QtCore.Qt.AlignCenter)
        self.label_work_experience.setObjectName("label_work_experience")
        self.horizontalLayout_12.addWidget(self.label_work_experience)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.radioButton_work_experience_1 = My_QRadioButton(self.widget_work_experience)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_work_experience_1.setFont(font)
        self.radioButton_work_experience_1.setObjectName("radioButton_work_experience_1")
        self.radioButton_work_experience_1.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                         "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.horizontalLayout_7.addWidget(self.radioButton_work_experience_1)
        self.radioButton_work_experience_1.clicked.connect(self.work_experience)
        self.radioButton_work_experience_2 = My_QRadioButton(self.widget_work_experience)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_work_experience_2.setFont(font)
        self.radioButton_work_experience_2.setObjectName("radioButton_work_experience_2")
        self.radioButton_work_experience_2.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                         "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.horizontalLayout_7.addWidget(self.radioButton_work_experience_2)
        self.radioButton_work_experience_2.clicked.connect(self.work_experience)
        self.radioButton_work_experience_3 = My_QRadioButton(self.widget_work_experience)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_work_experience_3.setFont(font)
        self.radioButton_work_experience_3.setObjectName("radioButton_work_experience_3")
        self.radioButton_work_experience_3.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                         "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.horizontalLayout_7.addWidget(self.radioButton_work_experience_3)
        self.radioButton_work_experience_3.clicked.connect(self.work_experience)
        self.radioButton_work_experience_4 = My_QRadioButton(self.widget_work_experience)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_work_experience_4.setFont(font)
        self.radioButton_work_experience_4.setObjectName("radioButton_work_experience_4")
        self.radioButton_work_experience_4.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                         "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.horizontalLayout_7.addWidget(self.radioButton_work_experience_4)
        self.radioButton_work_experience_4.clicked.connect(self.work_experience)
        self.radioButton_work_experience_5 = My_QRadioButton(self.widget_work_experience)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_work_experience_5.setFont(font)
        self.radioButton_work_experience_5.setObjectName("radioButton_work_experience_5")
        self.radioButton_work_experience_5.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                         "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.horizontalLayout_7.addWidget(self.radioButton_work_experience_5)
        self.radioButton_work_experience_5.clicked.connect(self.work_experience)
        self.radioButton_work_experience_6 = My_QRadioButton(self.widget_work_experience)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_work_experience_6.setFont(font)
        self.radioButton_work_experience_6.setObjectName("radioButton_work_experience_6")
        self.radioButton_work_experience_6.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                         "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.horizontalLayout_7.addWidget(self.radioButton_work_experience_6)
        self.radioButton_work_experience_6.clicked.connect(self.work_experience)
        self.radioButton_work_experience_7 = My_QRadioButton(self.widget_work_experience)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_work_experience_7.setFont(font)
        self.radioButton_work_experience_7.setObjectName("radioButton_work_experience_7")
        self.radioButton_work_experience_7.setStyleSheet("QRadioButton:hover{background-color:lightblue;}"
                                                         "QRadioButton:pressed{background-color:#F0F0F0;}")
        self.horizontalLayout_7.addWidget(self.radioButton_work_experience_7)
        self.radioButton_work_experience_7.clicked.connect(self.work_experience)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 9)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_12)
        self.verticalLayout.addWidget(self.widget_work_experience)
        self.line_row_5 = QtWidgets.QFrame(self.groupBox)
        self.line_row_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_row_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_row_5.setObjectName("line_row_5")
        self.verticalLayout.addWidget(self.line_row_5)
        self.widget_more = QtWidgets.QWidget(self.groupBox)
        self.widget_more.setObjectName("widget_more")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget_more)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_more = QtWidgets.QLabel(self.widget_more)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_more.setFont(font)
        self.label_more.setAlignment(QtCore.Qt.AlignCenter)
        self.label_more.setObjectName("label_more")
        self.horizontalLayout_10.addWidget(self.label_more)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.comboBox_education = QtWidgets.QComboBox(self.widget_more)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_education.setFont(font)
        self.comboBox_education.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_education.setStyleSheet("QComboBox{\n"
                                              "border: 1px solid gray;   /* 边框 */\n"
                                              "border-radius: 3px;   /* 圆角 */\n"
                                              "padding: 1px 18px 1px 3px;\n"
                                              "}\n"
                                              "QComboBox QAbstractItemView {\n"
                                              "outline: 0px solid gray;\n"
                                              "border: 1px solid black;\n"
                                              "selection-background-color: lightpink;\n"
                                              "}\n"
                                              "\n"
                                              "QComboBox QAbstractItemView::item {\n"
                                              "setAlignment: AlignCenter;\n"
                                              "}")
        self.comboBox_education.setEditable(True)
        self.comboBox_education.lineEdit().setPlaceholderText("学历")
        self.comboBox_education.lineEdit().setAlignment(QtCore.Qt.AlignCenter)
        self.comboBox_education.setDuplicatesEnabled(False)
        self.comboBox_education.setFrame(True)
        self.comboBox_education.setObjectName("comboBox_education")
        self.comboBox_education.addItem("")
        self.comboBox_education.addItem("")
        self.comboBox_education.addItem("")
        self.comboBox_education.addItem("")
        self.comboBox_education.addItem("")
        self.comboBox_education.addItem("")
        self.comboBox_education.addItem("")
        self.comboBox_education.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_education)
        self.comboBox_expected_position = QtWidgets.QComboBox(self.widget_more)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_expected_position.setFont(font)
        self.comboBox_expected_position.setStyleSheet("QComboBox{\n"
                                                      "border: 1px solid gray;   /* 边框 */\n"
                                                      "border-radius: 3px;   /* 圆角 */\n"
                                                      "padding: 1px 18px 1px 3px;\n"
                                                      "}\n"
                                                      "QComboBox QAbstractItemView {\n"
                                                      "outline: 0px solid gray;\n"
                                                      "border: 1px solid black;\n"
                                                      "selection-background-color: lightpink;\n"
                                                      "}\n"
                                                      "\n"
                                                      "QComboBox QAbstractItemView::item {\n"
                                                      "setAlignment: AlignCenter;\n"
                                                      "}")
        self.comboBox_expected_position.setEditable(True)
        self.comboBox_expected_position.lineEdit().setPlaceholderText("职位类型")
        self.comboBox_expected_position.lineEdit().setAlignment(QtCore.Qt.AlignCenter)
        self.comboBox_expected_position.setObjectName("comboBox_expected_position")
        self.comboBox_expected_position.addItem("")
        self.comboBox_expected_position.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_expected_position)
        self.comboBox_enterprise_scale = QtWidgets.QComboBox(self.widget_more)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_enterprise_scale.setFont(font)
        self.comboBox_enterprise_scale.setStyleSheet("QComboBox{\n"
                                                     "border: 1px solid gray;   /* 边框 */\n"
                                                     "border-radius: 3px;   /* 圆角 */\n"
                                                     "padding: 1px 18px 1px 3px;\n"
                                                     "}\n"
                                                     "QComboBox QAbstractItemView {\n"
                                                     "outline: 0px solid gray;\n"
                                                     "border: 1px solid black;\n"
                                                     "selection-background-color: lightpink;\n"
                                                     "}\n"
                                                     "\n"
                                                     "QComboBox QAbstractItemView::item {\n"
                                                     "setAlignment: AlignCenter;\n"
                                                     "}")
        self.comboBox_enterprise_scale.setEditable(True)
        self.comboBox_enterprise_scale.lineEdit().setPlaceholderText('企业规模')
        self.comboBox_enterprise_scale.lineEdit().setAlignment(QtCore.Qt.AlignCenter)
        self.comboBox_enterprise_scale.setObjectName("comboBox_enterprise_scale")
        self.comboBox_enterprise_scale.addItem("")
        self.comboBox_enterprise_scale.addItem("")
        self.comboBox_enterprise_scale.addItem("")
        self.comboBox_enterprise_scale.addItem("")
        self.comboBox_enterprise_scale.addItem("")
        self.comboBox_enterprise_scale.addItem("")
        self.comboBox_enterprise_scale.addItem("")
        self.comboBox_enterprise_scale.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_enterprise_scale)
        self.comboBox_financing_stage = QtWidgets.QComboBox(self.widget_more)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_financing_stage.setFont(font)
        self.comboBox_financing_stage.setStyleSheet("QComboBox{\n"
                                                    "border: 1px solid gray;   /* 边框 */\n"
                                                    "border-radius: 3px;   /* 圆角 */\n"
                                                    "padding: 1px 18px 1px 3px;\n"
                                                    "}\n"
                                                    "QComboBox QAbstractItemView {\n"
                                                    "outline: 0px solid gray;\n"
                                                    "border: 1px solid black;\n"
                                                    "selection-background-color: lightpink;\n"
                                                    "}\n"
                                                    "\n"
                                                    "QComboBox QAbstractItemView::item {\n"
                                                    "setAlignment: AlignCenter;\n"
                                                    "}")
        self.comboBox_financing_stage.setEditable(True)
        self.comboBox_financing_stage.lineEdit().setPlaceholderText('融资阶段')
        self.comboBox_financing_stage.lineEdit().setAlignment(QtCore.Qt.AlignCenter)
        self.comboBox_financing_stage.setObjectName("comboBox_financing_stage")
        self.comboBox_financing_stage.addItem("")
        self.comboBox_financing_stage.addItem("")
        self.comboBox_financing_stage.addItem("")
        self.comboBox_financing_stage.addItem("")
        self.comboBox_financing_stage.addItem("")
        self.comboBox_financing_stage.addItem("")
        self.comboBox_financing_stage.addItem("")
        self.comboBox_financing_stage.addItem("")
        self.comboBox_financing_stage.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_financing_stage)
        self.comboBox_enterprise_nature = QtWidgets.QComboBox(self.widget_more)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_enterprise_nature.setFont(font)
        self.comboBox_enterprise_nature.setStyleSheet("QComboBox{\n"
                                                      "border: 1px solid gray;   /* 边框 */\n"
                                                      "border-radius: 3px;   /* 圆角 */\n"
                                                      "padding: 1px 18px 1px 3px;\n"
                                                      "}\n"
                                                      "QComboBox QAbstractItemView {\n"
                                                      "outline: 0px solid gray;\n"
                                                      "border: 1px solid black;\n"
                                                      "selection-background-color: lightpink;\n"
                                                      "}\n"
                                                      "\n"
                                                      "QComboBox QAbstractItemView::item {\n"
                                                      "setAlignment: AlignCenter;\n"
                                                      "}")
        self.comboBox_enterprise_nature.setEditable(True)
        self.comboBox_enterprise_nature.lineEdit().setPlaceholderText('企业性质')
        self.comboBox_enterprise_nature.lineEdit().setAlignment(QtCore.Qt.AlignCenter)
        self.comboBox_enterprise_nature.setObjectName("comboBox_enterprise_nature")
        self.comboBox_enterprise_nature.addItem("")
        self.comboBox_enterprise_nature.addItem("")
        self.comboBox_enterprise_nature.addItem("")
        self.comboBox_enterprise_nature.addItem("")
        self.comboBox_enterprise_nature.addItem("")
        self.comboBox_enterprise_nature.addItem("")
        self.comboBox_enterprise_nature.addItem("")
        self.comboBox_enterprise_nature.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_enterprise_nature)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 9)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_10)
        self.verticalLayout.addWidget(self.widget_more)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_positions = QtWidgets.QLabel(widget_main_window)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_positions.setFont(font)
        self.label_positions.setObjectName("label_positions")
        self.horizontalLayout_11.addWidget(self.label_positions)
        self.label_position_num = QtWidgets.QLabel(widget_main_window)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_position_num.setFont(font)
        self.label_position_num.setObjectName("label_position_num")
        self.horizontalLayout_11.addWidget(self.label_position_num)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_main_submit = QtWidgets.QPushButton(widget_main_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_main_submit.sizePolicy().hasHeightForWidth())
        self.pushButton_main_submit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_main_submit.setFont(font)
        self.pushButton_main_submit.setStyleSheet("QPushButton{border-radius: 10px; \n"
                                                  "border: 2px solid gray;\n"
                                                  "padding: 3px 18px 3px 18px;}"
                                                  "QPushButton:hover{background-color:pink;}"
                                                  "QPushButton:pressed{background-color:#F0F0F0;}")
        self.pushButton_main_submit.setObjectName("pushButton_main_submit")
        self.horizontalLayout_3.addWidget(self.pushButton_main_submit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.setStretch(0, 6)
        self.verticalLayout_2.setStretch(1, 1)

        self.retranslateUi(widget_main_window)
        self.comboBox_education.setCurrentIndex(-1)
        self.comboBox_expected_position.setCurrentIndex(-1)
        self.comboBox_enterprise_nature.setCurrentIndex(-1)
        self.comboBox_enterprise_scale.setCurrentIndex(-1)
        self.comboBox_financing_stage.setCurrentIndex(-1)

        QtCore.QMetaObject.connectSlotsByName(widget_main_window)
        widget_main_window.setTabOrder(self.lineEdit_expected_salary_defined_first, self.lineEdit_expected_salary_defined_second)
        widget_main_window.setTabOrder(self.lineEdit_expected_salary_defined_second, self.lineEdit_search_keys)
        widget_main_window.setTabOrder(self.lineEdit_search_keys, self.comboBox_expected_position)
        widget_main_window.setTabOrder(self.comboBox_expected_position, self.pushButton_expected_salary_defined)

    def retranslateUi(self, widget_main_window):
        _translate = QtCore.QCoreApplication.translate
        widget_main_window.setWindowTitle(_translate("widget_main_window", "MainWindow"))
        self.groupBox.setTitle(_translate("widget_main_window", "搜索项"))
        self.lineEdit_search_keys.setPlaceholderText(_translate("widget_main_window", "关键词搜索"))
        self.label_famous_enterprise.setText(_translate("widget_main_window", "名       企"))
        self.radioButton_famous_enterprise_1.setText(_translate("widget_main_window", "财富中国500强"))
        self.radioButton_famous_enterprise_2.setText(_translate("widget_main_window", "创新企业100强"))
        self.radioButton_famous_enterprise_3.setText(_translate("widget_main_window", "制造业500强"))
        self.radioButton_famous_enterprise_4.setText(_translate("widget_main_window", "专精特新企业"))
        self.radioButton_famous_enterprise_5.setText(_translate("widget_main_window", "高新技术企业"))
        self.radioButton_famous_enterprise_6.setText(_translate("widget_main_window", "独角兽"))
        self.label_target_city.setText(_translate("widget_main_window", "城       市"))
        self.label_target_city_default.setText(_translate("widget_main_window", "全国(默认选项)"))
        self.label_expected_salary.setText(_translate("widget_main_window", "薪       资"))
        self.radioButton_expected_salary_1.setText(_translate("widget_main_window", "3K以下"))
        self.radioButton_expected_salary_2.setText(_translate("widget_main_window", "3K-5k"))
        self.radioButton_expected_salary_3.setText(_translate("widget_main_window", "5K-10k"))
        self.radioButton_expected_salary_4.setText(_translate("widget_main_window", "10K-20k"))
        self.radioButton_expected_salary_5.setText(_translate("widget_main_window", "20K-40k"))
        self.radioButton_expected_salary_6.setText(_translate("widget_main_window", "40K-60k"))
        self.radioButton_expected_salary_7.setText(_translate("widget_main_window", "60K以上"))
        self.groupBox_expected_salary_defined.setTitle(_translate("widget_main_window", "自定义"))
        self.label_expected_salary_k1.setText(_translate("widget_main_window", "k"))
        self.label_expected_salary_k2.setText(_translate("widget_main_window", "k"))
        self.pushButton_expected_salary_defined.setText(_translate("widget_main_window", "确定"))
        self.label_release_time.setText(_translate("widget_main_window", "发 布 时 间"))
        self.radioButton_release_time_1.setText(_translate("widget_main_window", "一天以内"))
        self.radioButton_release_time_2.setText(_translate("widget_main_window", "三天以内"))
        self.radioButton_release_time_3.setText(_translate("widget_main_window", "一周以内"))
        self.radioButton_release_time_4.setText(_translate("widget_main_window", "一个月以内"))
        self.label_work_experience.setText(_translate("widget_main_window", "经       验"))
        self.radioButton_work_experience_1.setText(_translate("widget_main_window", "应届生"))
        self.radioButton_work_experience_2.setText(_translate("widget_main_window", "实习生"))
        self.radioButton_work_experience_3.setText(_translate("widget_main_window", "1年以内"))
        self.radioButton_work_experience_4.setText(_translate("widget_main_window", "1-3年"))
        self.radioButton_work_experience_5.setText(_translate("widget_main_window", "3-5年"))
        self.radioButton_work_experience_6.setText(_translate("widget_main_window", "5-10年"))
        self.radioButton_work_experience_7.setText(_translate("widget_main_window", "十年以上"))
        self.label_more.setText(_translate("widget_main_window", "更       多"))

        # 学历
        self.comboBox_education.setItemText(0, _translate("widget_main_window", "博士"))
        self.comboBox_education.setItemText(1, _translate("widget_main_window", "MBA/EMBA"))
        self.comboBox_education.setItemText(2, _translate("widget_main_window", "硕士"))
        self.comboBox_education.setItemText(3, _translate("widget_main_window", "本科"))
        self.comboBox_education.setItemText(4, _translate("widget_main_window", "大专"))
        self.comboBox_education.setItemText(5, _translate("widget_main_window", "中专/中技"))
        self.comboBox_education.setItemText(6, _translate("widget_main_window", "高中"))
        self.comboBox_education.setItemText(7, _translate("widget_main_window", "初中及以下"))
        self.comboBox_education.activated.connect(self.more_education)

        # 职位类型
        self.comboBox_expected_position.setItemText(0, _translate("widget_main_window", "猎头职位"))
        self.comboBox_expected_position.setItemText(1, _translate("widget_main_window", "企业职位"))
        self.comboBox_expected_position.activated.connect(self.more_expected_position)

        # 企业规模
        self.comboBox_enterprise_scale.setItemText(0, _translate("widget_main_window", "1-49人"))
        self.comboBox_enterprise_scale.setItemText(1, _translate("widget_main_window", "50-99人"))
        self.comboBox_enterprise_scale.setItemText(2, _translate("widget_main_window", "100-499人"))
        self.comboBox_enterprise_scale.setItemText(3, _translate("widget_main_window", "500-999人"))
        self.comboBox_enterprise_scale.setItemText(4, _translate("widget_main_window", "1000-2000人"))
        self.comboBox_enterprise_scale.setItemText(5, _translate("widget_main_window", "2000-5000人"))
        self.comboBox_enterprise_scale.setItemText(6, _translate("widget_main_window", "5000-10000人"))
        self.comboBox_enterprise_scale.setItemText(7, _translate("widget_main_window", "10000人以上"))
        self.comboBox_enterprise_scale.activated.connect(self.more_enterprise_scale)

        # 融资阶段
        self.comboBox_financing_stage.setItemText(0, _translate("widget_main_window", "天使轮"))
        self.comboBox_financing_stage.setItemText(1, _translate("widget_main_window", "A轮"))
        self.comboBox_financing_stage.setItemText(2, _translate("widget_main_window", "B轮"))
        self.comboBox_financing_stage.setItemText(3, _translate("widget_main_window", "C轮"))
        self.comboBox_financing_stage.setItemText(4, _translate("widget_main_window", "D轮及以上"))
        self.comboBox_financing_stage.setItemText(5, _translate("widget_main_window", "已上市"))
        self.comboBox_financing_stage.setItemText(6, _translate("widget_main_window", "战略融资"))
        self.comboBox_financing_stage.setItemText(7, _translate("widget_main_window", "融资未公开"))
        self.comboBox_financing_stage.setItemText(8, _translate("widget_main_window", "其他"))
        self.comboBox_financing_stage.activated.connect(self.more_financing_stage)

        # 企业性质
        self.comboBox_enterprise_nature.setItemText(0, _translate("widget_main_window", "外商独资·外企办事处"))
        self.comboBox_enterprise_nature.setItemText(1, _translate("widget_main_window", "中外合营(合资·合作)"))
        self.comboBox_enterprise_nature.setItemText(2, _translate("widget_main_window", "私营·民营企业"))
        self.comboBox_enterprise_nature.setItemText(3, _translate("widget_main_window", "国有企业"))
        self.comboBox_enterprise_nature.setItemText(4, _translate("widget_main_window", "国内上市公司"))
        self.comboBox_enterprise_nature.setItemText(5, _translate("widget_main_window", "政府机关／非盈利机构"))
        self.comboBox_enterprise_nature.setItemText(6, _translate("widget_main_window", "事业单位"))
        self.comboBox_enterprise_nature.setItemText(7, _translate("widget_main_window", "其他"))
        self.comboBox_enterprise_nature.activated.connect(self.more_enterprise_nature)

        self.label_positions.setText(_translate("widget_main_window", "当前职位数："))
        self.label_position_num.setText(_translate("widget_main_window", "None"))
        self.pushButton_main_submit.setText(_translate("widget_main_window", "开始匹配"))
        # self.pushButton_main_submit.clicked.connect(self.main_submit)

        self.buttonGroup_expected_salary = My_QButtonGroup(self.widget_expected_salary)
        self.buttonGroup_expected_salary.addButton(self.radioButton_expected_salary_1, 1)
        self.buttonGroup_expected_salary.addButton(self.radioButton_expected_salary_2, 2)
        self.buttonGroup_expected_salary.addButton(self.radioButton_expected_salary_3, 3)
        self.buttonGroup_expected_salary.addButton(self.radioButton_expected_salary_4, 4)
        self.buttonGroup_expected_salary.addButton(self.radioButton_expected_salary_5, 5)
        self.buttonGroup_expected_salary.addButton(self.radioButton_expected_salary_6, 6)
        self.buttonGroup_expected_salary.addButton(self.radioButton_expected_salary_7, 7)

        self.buttonGroup_famous_enterprise = My_QButtonGroup(self.widget_famous_enterprise)
        self.buttonGroup_famous_enterprise.addButton(self.radioButton_famous_enterprise_1, 1)
        self.buttonGroup_famous_enterprise.addButton(self.radioButton_famous_enterprise_2, 2)
        self.buttonGroup_famous_enterprise.addButton(self.radioButton_famous_enterprise_3, 3)
        self.buttonGroup_famous_enterprise.addButton(self.radioButton_famous_enterprise_4, 4)
        self.buttonGroup_famous_enterprise.addButton(self.radioButton_famous_enterprise_5, 5)
        self.buttonGroup_famous_enterprise.addButton(self.radioButton_famous_enterprise_6, 6)

        self.buttonGroup_release_time = My_QButtonGroup(self.widget_release_time)
        self.buttonGroup_release_time.addButton(self.radioButton_release_time_1, 1)
        self.buttonGroup_release_time.addButton(self.radioButton_release_time_2, 2)
        self.buttonGroup_release_time.addButton(self.radioButton_release_time_3, 3)
        self.buttonGroup_release_time.addButton(self.radioButton_release_time_4, 4)

        self.buttonGroup_work_experience = My_QButtonGroup(self.widget_work_experience)
        self.buttonGroup_work_experience.addButton(self.radioButton_work_experience_1, 1)
        self.buttonGroup_work_experience.addButton(self.radioButton_work_experience_2, 2)
        self.buttonGroup_work_experience.addButton(self.radioButton_work_experience_3, 3)
        self.buttonGroup_work_experience.addButton(self.radioButton_work_experience_4, 4)
        self.buttonGroup_work_experience.addButton(self.radioButton_work_experience_5, 5)
        self.buttonGroup_work_experience.addButton(self.radioButton_work_experience_6, 6)
        self.buttonGroup_work_experience.addButton(self.radioButton_work_experience_7, 7)

    def none_event(self):
        pass
        # if self.buttonGroup_expected_salary.checkedButton().isChecked():
        #     print(self.buttonGroup_expected_salary.checkedButton().text(), 1)

    def search_keys(self):
        self.search_terms_dict['search_terms'] = self.lineEdit_search_keys.text()

    def famous_enterprise(self):
        if self.buttonGroup_famous_enterprise.checkedButton().isChecked():
            self.search_terms_dict['famous_enterprise'] = self.buttonGroup_famous_enterprise.checkedButton().text()

    def expected_salary_defined(self):
        if '确定' in self.pushButton_expected_salary_defined.sender().text():
            salary_defined = '自定义'
            if self.lineEdit_expected_salary_defined_second.text() <= self.lineEdit_expected_salary_defined_first.text():
                QtWidgets.QMessageBox.information(self.widget_expected_salary, 'Tip', '请重新输入')
                self.lineEdit_expected_salary_defined_first.clear()
                self.lineEdit_expected_salary_defined_second.clear()
            else:
                self.search_terms_dict['expected_salary'][0] = salary_defined
                self.search_terms_dict['expected_salary'][1] = self.lineEdit_expected_salary_defined_first.text()
                self.search_terms_dict['expected_salary'][2] = self.lineEdit_expected_salary_defined_second.text()
        elif self.buttonGroup_expected_salary.checkedButton().isChecked():
            self.search_terms_dict['expected_salary'][0] = self.buttonGroup_expected_salary.checkedButton().text()

    def release_time(self):
        if self.buttonGroup_release_time.checkedButton().isChecked():
            self.search_terms_dict['release_time'] = self.buttonGroup_release_time.checkedButton().text()

    def work_experience(self):
        if self.buttonGroup_work_experience.checkedButton().isChecked():
            self.search_terms_dict['work_experience'] = self.buttonGroup_work_experience.checkedButton().text()

    def more_education(self):
        self.search_terms_dict['education'] = self.comboBox_education.currentText()

    def more_expected_position(self):
        self.search_terms_dict['expected_position'] = self.comboBox_expected_position.currentText()

    def more_enterprise_scale(self):
        self.search_terms_dict['enterprise_scale'] = self.comboBox_enterprise_scale.currentText()

    def more_financing_stage(self):
        self.search_terms_dict['financing_stage'] = self.comboBox_financing_stage.currentText()

    def more_enterprise_nature(self):
        self.search_terms_dict['enterprise_nature'] = self.comboBox_enterprise_nature.currentText()

    def main_submit(self):
        return self.search_terms_dict

    def position_num(self, num='None'):
        self.label_position_num.setStyleSheet(f"qproperty-text:{num};")


class My_QRadioButton(QtWidgets.QRadioButton):
    QRadioButton_DoubleClicked = QtCore.pyqtSignal()
    # QRadioButton_Clicked = QtCore.pyqtSignal()

    def __init__(self, parent=None):
        super(My_QRadioButton, self).__init__(parent)

    def mouseDoubleClickEvent(self, QMouseEvent):
        self.setAutoExclusive(False)
        self.setChecked(False)
        self.setAutoExclusive(True)
        self.QRadioButton_DoubleClicked.emit()

    # def mouseReleaseEvent(self, QMouseEvent):
    #     self.QRadioButton_Clicked.emit()

    def double_connect_customized_slot(self, func):
        self.QRadioButton_DoubleClicked.connect(func)

    # def sender_connect_customized_slot(self, func):
    #     self.QRadioButton_sender.connect(func)


class My_QButtonGroup(QtWidgets.QButtonGroup):
    QButtonGroup_Pressed = QtCore.pyqtSignal()

    def __init__(self, parent=None):
        super(My_QButtonGroup, self).__init__(parent)

    def buttonPressed(self, QAbstractButton):
        self.checkedButton().setAutoExclusive(False)
        self.checkedButton().setChecked(False)
        self.checkedButton().setAutoExclusive(True)
        self.QButtonGroup_Pressed.emit()

    def pressed_connect_customized_slot(self, func):
        self.QButtonGroup_Pressed.connect(func)
