# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'operation_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


# class Ui_Form_login(object):
#     status = None
#
#     def setupUi(self, Form_login):
#         Form_login.setObjectName("Form_login")
#         Form_login.resize(400, 200)
#         Form_login.setFixedSize(400, 200)
#         self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form_login)
#         self.verticalLayout_3.setObjectName("verticalLayout_3")
#         self.label_login_title = QtWidgets.QLabel(Form_login)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.label_login_title.sizePolicy().hasHeightForWidth())
#         self.label_login_title.setSizePolicy(sizePolicy)
#         font = QtGui.QFont()
#         font.setFamily("微软雅黑")
#         font.setPointSize(20)
#         font.setBold(True)
#         font.setWeight(75)
#         font.setKerning(True)
#         self.label_login_title.setFont(font)
#         self.label_login_title.setLayoutDirection(QtCore.Qt.LeftToRight)
#         self.label_login_title.setAlignment(QtCore.Qt.AlignCenter)
#         self.label_login_title.setObjectName("label_login_title")
#         self.verticalLayout_3.addWidget(self.label_login_title)
#         spacerItem = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
#         self.verticalLayout_3.addItem(spacerItem)
#         self.widget = QtWidgets.QWidget(Form_login)
#         self.widget.setObjectName("widget")
#         self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
#         self.horizontalLayout.setObjectName("horizontalLayout")
#         spacerItem1 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
#         self.horizontalLayout.addItem(spacerItem1)
#         self.verticalLayout = QtWidgets.QVBoxLayout()
#         self.verticalLayout.setObjectName("verticalLayout")
#         self.label_login_user = QtWidgets.QLabel(self.widget)
#         font = QtGui.QFont()
#         font.setPointSize(13)
#         font.setBold(True)
#         font.setWeight(75)
#         self.label_login_user.setFont(font)
#         self.label_login_user.setObjectName("label_login_user")
#         self.verticalLayout.addWidget(self.label_login_user)
#         self.label_login_password = QtWidgets.QLabel(self.widget)
#         font = QtGui.QFont()
#         font.setPointSize(13)
#         font.setBold(True)
#         font.setWeight(75)
#         self.label_login_password.setFont(font)
#         self.label_login_password.setObjectName("label_login_password")
#         self.verticalLayout.addWidget(self.label_login_password)
#         self.horizontalLayout.addLayout(self.verticalLayout)
#         self.verticalLayout_2 = QtWidgets.QVBoxLayout()
#         self.verticalLayout_2.setObjectName("verticalLayout_2")
#         self.lineEdit_login_user = QtWidgets.QLineEdit(self.widget)
#         font = QtGui.QFont()
#         font.setPointSize(10)
#
#         self.reg = QtCore.QRegExp('[0-9]+$')
#         self.validator = QtGui.QRegExpValidator(self.reg)
#
#         self.lineEdit_login_user.setFont(font)
#         self.lineEdit_login_user.setStyleSheet("border: 1px solid gray;   /* 边框 */\n"
#                                                "border-radius: 3px;   /* 圆角 */\n"
#                                                "padding: 1px 18px 1px 3px;\n"
#                                                "")
#         self.lineEdit_login_user.setText("")
#         self.lineEdit_login_user.setObjectName("lineEdit_login_user")
#         self.lineEdit_login_user.setValidator(self.validator)
#         self.verticalLayout_2.addWidget(self.lineEdit_login_user)
#         self.lineEdit_login_password = QtWidgets.QLineEdit(self.widget)
#         font = QtGui.QFont()
#         font.setPointSize(10)
#         self.lineEdit_login_password.setFont(font)
#         self.lineEdit_login_password.setStyleSheet("border: 1px solid gray;   /* 边框 */\n"
#                                                    "border-radius: 3px;   /* 圆角 */\n"
#                                                    "padding: 1px 18px 1px 3px;\n"
#                                                    "")
#         self.lineEdit_login_password.setText("")
#         self.lineEdit_login_password.setObjectName("lineEdit_login_password")
#         self.lineEdit_login_password.setValidator(self.validator)
#         self.verticalLayout_2.addWidget(self.lineEdit_login_password)
#         self.horizontalLayout.addLayout(self.verticalLayout_2)
#         spacerItem2 = QtWidgets.QSpacerItem(69, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
#         self.horizontalLayout.addItem(spacerItem2)
#         self.verticalLayout_3.addWidget(self.widget)
#         spacerItem3 = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
#         self.verticalLayout_3.addItem(spacerItem3)
#         self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
#         self.horizontalLayout_3.setObjectName("horizontalLayout_3")
#         spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
#         self.horizontalLayout_3.addItem(spacerItem4)
#         self.pushButton_login = QtWidgets.QPushButton(Form_login)
#         self.pushButton_login.setStyleSheet("QPushButton{\n"
#                                             "border: 1px solid gray;   /* 边框 */\n"
#                                             "border-radius: 3px;   /* 圆角 */\n"
#                                             "}\n"
#                                             "QPushButton:hover{background-color:pink;}\n"
#                                             "QPushButton:pressed{background-color:#F0F0F0;}")
#         self.pushButton_login.setObjectName("pushButton_login")
#         # self.pushButton_login.clicked.connect(self.login_submit)
#         self.horizontalLayout_3.addWidget(self.pushButton_login)
#         spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
#         self.horizontalLayout_3.addItem(spacerItem5)
#         self.pushButton_exit = QtWidgets.QPushButton(Form_login)
#         self.pushButton_exit.setStyleSheet("QPushButton{\n"
#                                            "border: 1px solid gray;   /* 边框 */\n"
#                                            "border-radius: 3px;   /* 圆角 */\n"
#                                            "}\n"
#                                            "QPushButton:hover{background-color:pink;}\n"
#                                            "QPushButton:pressed{background-color:#F0F0F0;}")
#         self.pushButton_exit.setObjectName("pushButton_exit")
#         self.horizontalLayout_3.addWidget(self.pushButton_exit)
#         spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
#         self.horizontalLayout_3.addItem(spacerItem6)
#         self.horizontalLayout_3.setStretch(0, 2)
#         self.horizontalLayout_3.setStretch(1, 2)
#         self.horizontalLayout_3.setStretch(2, 1)
#         self.horizontalLayout_3.setStretch(3, 2)
#         self.horizontalLayout_3.setStretch(4, 2)
#         self.verticalLayout_3.addLayout(self.horizontalLayout_3)
#         spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
#         self.verticalLayout_3.addItem(spacerItem7)
#
#         self.retranslateUi(Form_login)
#         self.pushButton_exit.clicked.connect(Form_login.close)
#         QtCore.QMetaObject.connectSlotsByName(Form_login)
#
#     def retranslateUi(self, Form_login):
#         _translate = QtCore.QCoreApplication.translate
#         Form_login.setWindowTitle(_translate("Form_login", "Login"))
#         self.label_login_title.setText(_translate("Form_login", "职 位 匹 配 器"))
#         self.label_login_user.setText(_translate("Form_login", "用户名："))
#         self.label_login_password.setText(_translate("Form_login", "密  码："))
#         self.pushButton_login.setText(_translate("Form_login", "登录"))
#         self.pushButton_exit.setText(_translate("Form_login", "退出"))
#
#     def login_submit(self):
#         # return self.lineEdit_login_user.text(), self.lineEdit_login_password.text()
#         self.status = True
#
#     def login_determine(self, status=False):
#         if not status:
#             QtWidgets.QMessageBox.information(self.widget, 'Tip', '请重新输入用户名/密码')
#         else:
#             pass
#         return status
